version: '3.8'

services:
  django:
    build: .
    ports:
      - "8001:8000"  # Expose a different port to the host
    env_file:
      - .env
    volumes:
      - ./itbrat:/code
      - media_volume:/code/media
      - static_volume:/code/static
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 --workers 3 config.wsgi:application"
    depends_on:
      - db

  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"  # Forward port 80 on host to port 80 in container
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/code/static
      - media_volume:/code/media
    depends_on:
      - django

volumes:
  postgres_data:
  media_volume:
  static_volume:
